In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset_Facebook.csv", sep=';')

In [3]:
df.size

9500

In [4]:
df.shape

(500, 19)

In [5]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [6]:
print(df)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
..                ...     ...       ...         ...           ...        ...
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
..    ...                        ...                              ...
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
1                                                 1108
2                                                  132
3                                                 1386
4                                                  396
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
1          5   130.0   29.0                 164
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[500 rows x 19 columns]

In [7]:
data1 = df.iloc[:10,:]

data1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142

In [8]:
data2 = df.iloc[10:20,:]

data2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42

In [9]:
data3 = df.iloc[20:30,:]

data3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174

In [10]:
mData = pd.concat([data2, data1])
mData.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [11]:
sortedMData = mData.sort_values("Lifetime Post Total Impressions", ascending=True)
sortedMData

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713

In [12]:
sortedMDataDec = mData.sort_values("Lifetime Post Total Impressions", ascending=False)
sortedMDataDec

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42

In [13]:
trans = sortedMDataDec.transpose()
trans

,17,3,10,14,7,8,5,15,6,1,4,9,18,11,12,0,13,2,16,19
Page total likes,138414,139441,139441,138414,139441,139441,139441,138414,139441,139441,139441,139441,138414,139441,139441,139441,139441,139441,138414,138414
Type,Photo,Photo,Status,Photo,Photo,Status,Status,Status,Photo,Status,Photo,Photo,Status,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,1,2,2,2,3,2,2,2,3,2,2,3,3,2,2,2,2,3,3,3
Post Month,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Post Weekday,2,2,5,4,7,7,1,3,1,3,2,6,2,5,5,4,5,3,3,1
Post Hour,12,10,10,5,9,3,9,10,3,10,3,10,3,10,10,3,3,3,3,11
Paid,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,53264,50128,21744,22784,13720,11844,10472,10060,11692,10460,7244,4694,3930,3112,2847,2752,2549,2413,1722,1591
Lifetime Post Total Impressions,111785,87991,42334,39941,24137,22538,20849,19680,19479,19057,13594,8668,7509,5590,5133,5091,4896,4373,2981,2825
Lifetime Engaged Users,1706,2211,4258,887,537,1530,1191,1264,481,1457,671,280,130,208,193,178,249,177,163,121
Lifetime Post Consumers,1103,790,4100,337,232,1407,1073,1209,265,1361,410,183,86,127,115,109,134,113,123,88
Lifetime Post Consumptions,1655,1119,4540,417,305,1692,1389,1425,364,1674,580,250,112,145,133,159,168,154,148,111
Lifetime Post Impressions by people who have liked your Page,92512,61027,37849,34415,19728,15220,16034,17272,15432,11710,6228,4309,5009,3887,3779,3078,3631,2812,1868,2116
Lifetime Post reach by people who like your Page,39776,32048,18952,19312,11056,7912,7852,8548,9328,6112,3200,2324,2410,2174,2072,1640,1917,1503,1050,1161
Lifetime People who have liked your Page and engaged with your post,1307,1386,3798,684,422,1250,1016,1162,379,1108,396,199,101,165,152,119,183,132,123,100
comment,15,58,0,2,0,0,1,4,3,5,19,3,4,0,0,4,5,0,2,0
like,678.0,1572.0,233.0,577.0,325.0,161.0,152.0,86.0,249.0,130.0,325.0,113.0,54.0,88.0,90.0,79.0,137.0,66.0,40.0,34.0
share,20.0,147.0,19.0,20.0,14.0,31.0,33.0,18.0,27.0,29.0,49.0,26.0,17.0,18.0,14.0,17.0,10.0,14.0,12.0,8.0
Total Interactions,713,1777,252,599,339,192,186,108,279,164,393,142,75,106,104,100,152,80,54,42

In [14]:
mData1 = mData.copy

In [16]:
mData1

<bound method NDFrame.copy of     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
10            139441  Status         2          12             5         10
11            139441   Photo         2          12             5         10
12            139441   Photo         2          12             5         10
13            139441   Photo         2          12             5          3
14            138414   Photo         2          12             4          5
15            138414  Status         2          12             3         10
16            138414   Photo         3          12             3          3
17            138414   Photo         1          12             2         12
18            138414  Status         3          12             2          3
19            138414   Photo         3          12             1         11
0             139441   Photo         2          12             4          3
1             139441  Status         2          12             3         10
2             139441   Photo         3          12             3          3
3             139441   Photo         2          12             2         10
4             139441   Photo         2          12             2          3
5             139441  Status         2          12             1          9
6             139441   Photo         3          12             1          3
7             139441   Photo         3          12             7          9
8             139441  Status         2          12             7          3
9             139441   Photo         3          12             6         10

    Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
10   0.0                      21744                            42334
11   0.0                       3112                             5590
12   0.0                       2847                             5133
13   0.0                       2549                             4896
14   1.0                      22784                            39941
15   0.0                      10060                            19680
16   0.0                       1722                             2981
17   1.0                      53264                           111785
18   0.0                       3930                             7509
19   0.0                       1591                             2825
0    0.0                       2752                             5091
1    0.0                      10460                            19057
2    0.0                       2413                             4373
3    1.0                      50128                            87991
4    0.0                       7244                            13594
5    0.0                      10472                            20849
6    1.0                      11692                            19479
7    1.0                      13720                            24137
8    0.0                      11844                            22538
9    0.0                       4694                             8668

    Lifetime Engaged Users  Lifetime Post Consumers  \
10                    4258                     4100
11                     208                      127
12                     193                      115
13                     249                      134
14                     887                      337
15                    1264                     1209
16                     163                      123
17                    1706                     1103
18                     130                       86
19                     121                       88
0                      178                      109
1                     1457                     1361
2                      177                      113
3                     2211                      790
4                      671                      410
5                     1191                     1073
6                      481                      265
7                      537                      232
8                     1530                     1407
9                      280                      183

    Lifetime Post Consumptions  \
10                        4540
11                         145
12                         133
13                         168
14                         417
15                        1425
16                         148
17                        1655
18                         112
19                         111
0                          159
1                         1674
2                          154
3                         1119
4                          580
5                         1389
6                          364
7                          305
8                         1692
9                          250

    Lifetime Post Impressions by people who have liked your Page  \
10                                              37849
11                                               3887
12                                               3779
13                                               3631
14                                              34415
15                                              17272
16                                               1868
17                                              92512
18                                               5009
19                                               2116
0                                                3078
1                                               11710
2                                                2812
3                                               61027
4                                                6228
5                                               16034
6                                               15432
7                                               19728
8                                               15220
9                                                4309

    Lifetime Post reach by people who like your Page  \
10                                             18952
11                                              2174
12                                              2072
13                                              1917
14                                             19312
15                                              8548
16                                              1050
17                                             39776
18                                              2410
19                                              1161
0                                               1640
1                                               6112
2                                               1503
3                                              32048
4                                               3200
5                                               7852
6                                               9328
7                                              11056
8                                               7912
9                                               2324

    Lifetime People who have liked your Page and engaged with your post  \
10                                               3798
11                                                165
12                                                152
13                                                183
14                                                684
15                                               1162
16                                                123
17                                               1307
18                                                101
19                                                100
0                                                 119
1                                                1108
2                                                 132
3                                                1386
4                                                 396
5                                                1016
6                                                 379
7                                                 422
8                                                1250
9                                                 199

    comment    like  share  Total Interactions
10        0   233.0   19.0                 252
11        0    88.0   18.0                 106
12        0    90.0   14.0                 104
13        5   137.0   10.0                 152
14        2   577.0   20.0                 599
15        4    86.0   18.0                 108
16        2    40.0   12.0                  54
17       15   678.0   20.0                 713
18        4    54.0   17.0                  75
19        0    34.0    8.0                  42
0         4    79.0   17.0                 100
1         5   130.0   29.0                 164
2         0    66.0   14.0                  80
3        58  1572.0  147.0                1777
4        19   325.0   49.0                 393
5         1   152.0   33.0                 186
6         3   249.0   27.0                 279
7         0   325.0   14.0                 339
8         0   161.0   31.0                 192
9         3   113.0   26.0                 142  >

In [17]:
df.pivot(index="like", columns=["Lifetime Post Consumptions"], values=["comment","Lifetime Engaged Users","Lifetime Post Total Impressions"])

                           comment                                            \
Lifetime Post Consumptions   9     19    20    26    31    49    55    70
like
NaN                            NaN   NaN   NaN   NaN   NaN   0.0   NaN   NaN
0.0                            0.0   0.0   0.0   NaN   0.0   NaN   0.0   NaN
1.0                            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2.0                            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3.0                            NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...                            ...   ...   ...   ...   ...   ...   ...   ...
1572.0                         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1622.0                         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1639.0                         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1998.0                         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
5172.0                         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

                                        ... Lifetime Post Total Impressions  \
Lifetime Post Consumptions 71    95     ...                           8049
like                                    ...
NaN                          NaN   NaN  ...                             NaN
0.0                          NaN   NaN  ...                             NaN
1.0                          NaN   NaN  ...                             NaN
2.0                          NaN   NaN  ...                             NaN
3.0                          NaN   NaN  ...                             NaN
...                          ...   ...  ...                             ...
1572.0                       NaN   NaN  ...                             NaN
1622.0                       NaN   NaN  ...                             NaN
1639.0                       NaN   NaN  ...                             NaN
1998.0                       NaN   NaN  ...                             NaN
5172.0                       NaN   NaN  ...                             NaN

                                                                            \
Lifetime Post Consumptions 8308  8415  9237  9614  11064 12074 14974 18115
like
NaN                          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
0.0                          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1.0                          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2.0                          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3.0                          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...                          ...   ...   ...   ...   ...   ...   ...   ...
1572.0                       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1622.0                       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1639.0                       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1998.0                       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
5172.0                       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN


Lifetime Post Consumptions 19779
like
NaN                          NaN
0.0                          NaN
1.0                          NaN
2.0                          NaN
3.0                          NaN
...                          ...
1572.0                       NaN
1622.0                       NaN
1639.0                       NaN
1998.0                       NaN
5172.0                       NaN

[258 rows x 1320 columns]